- .github/workflows/build_engine.yml
- .github/workflows/test_engine.yml
- engines/dhewm3/build.sh
> Pull Request CI

- common/lib.sh
- common/start_build.sh
- docs/Creating_a_Package.md
- engines/dhewm3/env.sh
> Support for copying license files

- common/lib.sh
- docs/Creating_a_Package.md
- engines/arxlibertatis/env.sh
> Additional licenses

- metadata/packages.html
- metadata/packages.json
> Add license information

- .github/workflows/build_engine.yml
- engines/ioquake3/LICENSE
- engines/ioquake3/build.sh
- engines/ioquake3/env.sh
- metadata/packages.json
> Add ioquake 3 engine

- engines/dxx-rebirth/build.sh
> Use SDL2 for dxx-rebirth

- .github/workflows/build_engine.yml
- common/lib.sh
- common/package.sh
- common/start_build.sh
- engines/dhewm3/build.sh
- engines/dhewm3/env.sh
- engines/julius/build.sh
> Shared packages workflow

- engines/arxlibertatis/build.sh
- engines/arxlibertatis/env.sh
> Change to use common package for arxlibertatis

- engines/opengothic/build.sh
> Update opengothic engine version

- engines/dxx-rebirth/build.sh
- engines/dxx-rebirth/env.sh
> Switch to gcc 9 and newer version of dxx-rebirth

- engines/ut2004/assets/run-ut2004.sh
- engines/ut2004/build.sh
- metadata/packages.json
> Fixes for ut 2004

- engines/ut2004/assets/run-ut2004.sh
- engines/ut2004/build.sh
- engines/ut2004/env.sh
> UT 2004 Dependency Improvements

- docs/Creating_a_Package.md
- engines/ut2004/assets/setup-ut2004.sh
- engines/ut2004/assets/uninstall-ut2004.sh
- engines/ut2004/build.sh
- metadata/packages.json
> UT 2004 Script Improvements

- engines/quake4/assets/run-quake4.sh
- engines/quake4/assets/setup-quake4.sh
- engines/quake4/assets/uninstall-quake4.sh
- engines/quake4/build.sh
- metadata/packages.json
> Quake4 scripts

- engines/quake4/assets/setup-quake4.sh
> Quake 4 - Remove install file once complete

- engines/ut2004/build.sh
> Update ut 2004 sdlcl

- engines/julius/build.sh
- metadata/packages.json
> julius - Upgrade to 1.4.1

- engines/vkquake/build.sh
- metadata/packages.json
> vkquake - Upgrade to 1.04.1

- engines/fs2open/build.sh
- engines/fs2open/env.sh
- metadata/packages.json
> fs2open - Upgrade to latest master

- engines/ut99/assets/run-ut99.sh
> ut99 - Add fix for padsp not loading 32-bit lib

- engines/openrct2/assets/run-openrct2.sh
- metadata/packages.json
> openrct2 - Automatically disable steam overlay

- engines/ut2004/assets/setup-ut2004.sh
- metadata/packages.json
> ut2004 - Add foxWSFix

- engines/ut99/assets/run-ut99.sh
- engines/ut99/assets/setup-ut99.sh
> ut99 - pulseaudio find and non-nvidia graphics settings

- engines/openrct2/assets/run-openrct2.sh
- engines/openrct2/assets/setup-rct1.sh
- engines/openrct2/assets/setup-rct2.sh
- engines/openrct2/build.sh
- engines/openrct2/env.sh
- metadata/packages.json
> openrct2 - Add support for RCT1

- engines/opengothic/assets/run-gothic2.sh
- engines/opengothic/build.sh
- metadata/packages.json
> Opengothic upgrade

- engines/openxcom-oxce/assets/run-tftd.sh
- engines/openxcom-oxce/assets/run-ufo.sh
- engines/openxcom-oxce/build.sh
- engines/openxcom-oxce/env.sh
- metadata/packages.json
> Openxcom OXCE

- engines/common-qt5/build.sh
> qt5 x11 fix

- engines/openmw/build.sh
- engines/openmw/env.sh
> openmw - wizard fixes

- engines/dosbox-staging/assets/run-dosbox-staging.sh
- engines/dosbox-staging/build.sh
- engines/dosbox-staging/env.sh
- metadata/packages.json
> dosbox-staging

- common/lib.sh
- engines/openxray/assets/run-openxray-clearsky.sh
- engines/openxray/build.sh
> Openxray sdl fix

- engines/dosbox-staging/build.sh
- metadata/packages.json
> dosbox-staging - Upgrade to 0.75.1

- engines/opengothic/build.sh
- engines/opengothic/env.sh
- metadata/packages.json
> opengothic - Upgrade to v0.29

- engines/opengothic/build.sh
- metadata/packages.json
> opengothic - Upgrade

- engines/classic-rbdoom-3-bfg/assets/run-classic-rbdoom-3-bfg.sh
- engines/classic-rbdoom-3-bfg/assets/setup-classic-rbdoom-3-bfg.sh
- engines/classic-rbdoom-3-bfg/build-ffmpeg.sh
- engines/classic-rbdoom-3-bfg/build.sh
- engines/classic-rbdoom-3-bfg/env.sh
- metadata/packages.json
> Add classic-rbdoom-3-bfg

- engines/classic-rbdoom-3-bfg/build.sh
- engines/classic-rbdoom-3-bfg/env.sh
> classic-rbdoom-3-bfg - Use Ubuntu 18.04

- engines/chocolate-doom/assets/run-chocolate-doom.sh
- engines/chocolate-doom/assets/run-chocolate-heretic.sh
- engines/chocolate-doom/assets/run-chocolate-hexen.sh
- engines/chocolate-doom/build.sh
- engines/chocolate-doom/env.sh
- metadata/packages.json
> Chocolate doom

- engines/serious-engine/assets/run-dhewm3.sh
- engines/serious-engine/build.sh
- engines/serious-engine/env.sh
- metadata/packages.json
> Serious engine

- engines/reminiscence/assets/run-flashback.sh
- engines/reminiscence/build.sh
- engines/reminiscence/env.sh
- metadata/packages.json
> Reminiscence

- engines/ut99/assets/run-ut99-469a.sh
- engines/ut99/assets/setup-ut99-469a.sh
- engines/ut99/assets/uninstall-ut99-469a.sh
- metadata/packages.json
> ut99 - Add 469a version support

- engines/opengothic/build.sh
- metadata/packages.json
> opengothic - Update to v0.31

- engines/re3/build.sh
- metadata/packages.json
> re3 - Update to c31e3e6

- engines/dosbox-staging/build.sh
- metadata/packages.json
> dosbox-staging - Update to 0.75.2

- engines/julius/build.sh
- metadata/packages.json
> julius - Update to 1.5.0

- engines/re3/build.sh
- metadata/packages.json
> re3 - Update to 4cfb3b0984c1de2820691b4b5f1c63cd19c498fb

- engines/julius/build.sh
- metadata/packages.json
> julius - Update to 1.5.1

- engines/realrtcw/build.sh
- metadata/packages.json
> realrtcw - Update to a1344ab

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.9.0

- engines/opengothic/build.sh
- metadata/packages.json
> opengothic - Update to 0.32

- engines/reone/build-ffmpeg.sh
- engines/reone/build.sh
- engines/reone/env.sh
- metadata/packages.json
> reone - Update to 0.10.0

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.11

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.11.1

- engines/realrtcw/build.sh
- metadata/packages.json
> realrtcw - Update to latest

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.12.0

- engines/openxray/build.sh
> openxray - Update December 2020 Preview

- engines/fs2open/build.sh
- metadata/packages.json
> fs2open - Update to 20.1 RC1

- engines/classic-rbdoom-3-bfg/build.sh
- metadata/packages.json
> classic rbdoom 3 bfg - Update to 1.2.7

- engines/re3/build.sh
- metadata/packages.json
> re3 - Update to 14f7dba

- engines/reVC/build.sh
- metadata/packages.json
> reVC - Update to c93fb5e443f9afe082abf708918fcd3db807596d

- engines/julius/build.sh
- metadata/packages.json
> julius - Update to 1.6.0

- engines/cortex-command/build.sh
- engines/cortex-command/env.sh
- metadata/packages.json
> cortex command - Update to pre release 3.0

- engines/fs2open/build.sh
- metadata/packages.json
> fs2open - Update to Release 21.0 RC2

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.13.0

- engines/fs2open/build.sh
- metadata/packages.json
> fs2open - Update to 21.0 RC3

- engines/wrath-darkplaces/build.sh
- engines/wrath-darkplaces/env.sh
- metadata/packages.json
> wrath-darkplaces

- engines/serioussam2/assets/run-serioussam2.sh
- engines/serioussam2/assets/serioussam2
- engines/serioussam2/assets/setup-serioussam2.sh
- engines/serioussam2/build.sh
- engines/serioussam2/env.sh
- metadata/packages.json
> serioussam2

- engines/quake3e/build.sh
- metadata/packages.json
> quake3e - Update to 2021-01-16

- engines/vkquake/build.sh
- metadata/packages.json
> vkquake - Update to 1.05.2

- metadata/packages.json
> openxray - engine name correction (openxray -> OpenXRay)

- engines/sonic-cd-11-decomp/build.sh
- engines/sonic-cd-11-decomp/env.sh
- metadata/packages.json
> Sonic cd 11

- metadata/packages.json
> ut2004 - Update foxWSFix-UT2k4 to 2.1.0

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.14.0

- engines/alive_reversing/build.sh
- engines/alive_reversing/env.sh
- metadata/packages.json
> alive_reversing

- engines/realrtcw/build.sh
- metadata/packages.json
> realrtcw - Update to 1/24/2021 release

- engines/fs2open/build.sh
- metadata/packages.json
> fs2open - Update to 21.0 RC5

- engines/unreal-gold/assets/README.txt
- engines/unreal-gold/assets/run-unreal.sh
- engines/unreal-gold/build.sh
- engines/unreal-gold/env.sh
- metadata/packages.json
> unreal-gold

- engines/sonic-cd-11-decomp/build.sh
- metadata/packages.json
> sonic-cd-11-decomp - Update to v1.1.0

- engines/unreal-gold/assets/run-unreal.sh
- engines/unreal-gold/build.sh
- engines/unreal-gold/env.sh
- engines/unreal-gold/patches/0001-Force-32-bit.patch
> unreal-gold - Add sdlcl

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.15.0

- engines/xash3d-fwgs-19/assets/run-absolute-zero.sh
- engines/xash3d-fwgs-19/assets/setup-absolute-zero.sh
- engines/xash3d-fwgs-19/build.sh
- engines/xash3d-fwgs-19/env.sh
- metadata/packages.json
> xash3d-fwgs-19 - Added support for absolute zero via upstream download

- engines/hammerofthyrion/assets/hammerofthyrion.sh
- engines/hammerofthyrion/build.sh
- engines/hammerofthyrion/env.sh
- engines/hammerofthyrion/patches/libmad-0.15.1b-fixes-1.patch
- metadata/packages.json
> Hammerofthyrion

- engines/reVC/build.sh
- metadata/packages.json
> reVC - Update to ddcc19d7cf4b5a76fadc224966a0fa074b142592

- engines/re3/build.sh
- metadata/packages.json
> re3 - Update to 8d27dba4cdec4d3b39bf87ce5baef5962e58312c

- engines/commander-genius/assets/run-commander.sh
- engines/commander-genius/build.sh
- engines/commander-genius/env.sh
- metadata/packages.json
> commander-genius

- engines/eduke32/assets/run-nam.sh
- engines/eduke32/assets/run-ww2gi.sh
> eduke32 - Fix game launching

- engines/doomsday/env.sh
- engines/gzdoom/env.sh
- metadata/packages.json
> Added support for Hexen Deathkings

- engines/openloco/build.sh
- metadata/packages.json
> openloco - Update to 21.03

- engines/reone/build.sh
- engines/reone/env.sh
- metadata/packages.json
> reone - Update to 0.16.0

- engines/ut99/assets/run-ut99-436.sh
- engines/ut99/assets/run-ut99-451.sh
- engines/ut99/assets/run-ut99-469a.sh
- engines/ut99/assets/run-ut99-469b.sh
> ut99 - Add check for opensuse pulseaudio

- engines/reone/build.sh
> reone - Update to 0.16.1

- engines/warzone2100/build.sh
- metadata/packages.json
> warzone 2100 - Update to 4.0.0-beta2

- engines/openapoc/build.sh
- metadata/packages.json
> openapoc - Update to Alpha build v0.386

- engines/warzone2100/build.sh
- metadata/packages.json
> warzone2100 - Update to 4.0.0-beta3

- engines/quake3e/build.sh
- metadata/packages.json
> quake3e - Update to 2021-03-28

- engines/fs2open/build.sh
- metadata/packages.json
> fs2open - Update to 21.2.0 RC1

- engines/openhexagon/build.sh
- metadata/packages.json
> openhexagon - Update to 7f47e31

- engines/engge/build.sh
- metadata/packages.json
> engge - Update to v0.8.0-beta

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.17.0

- engines/openloco/build.sh
- engines/openloco/env.sh
- metadata/packages.json
> openloco - Update to 21.04

- engines/opengothic/build.sh
- metadata/packages.json
> opengothic - Update to v1.0.1035

- engines/warzone2100/build.sh
- metadata/packages.json
> warzone2100 - Update to 4.0.1

- engines/rbdoom-3-bfg/build.sh
- metadata/packages.json
> rbdoom-3-bfg - Update to latest master (09c9f25)

- engines/fs2open/build.sh
- metadata/packages.json
> fs2open - Update to 21.2.0 RC3

- engines/openhexagon/build.sh
- metadata/packages.json
> openhexagon - Update to 2.0.5

- engines/fs2open/build.sh
- metadata/packages.json
> fs2open - Update to 21.2.0

- engines/realrtcw/build.sh
- metadata/packages.json
> realrtcw - Update to 3.2

- engines/reone/build.sh
- metadata/packages.json
> reone - Update to 0.18.0

- engines/sonic-cd-11-decomp/build.sh
- metadata/packages.json
> sonic-cd-11-decomp - Update to v1.1.2

- common/lib.sh
- common/start_build.sh
- engines/openloco/build.sh
- engines/openloco/env.sh
- metadata/packages.json
> openloco - Update to 21.05

- engines/augustus/build.sh
- metadata/packages.json
> augustus - Update to 3.0

- engines/reVC/assets/run-reVC.sh
- engines/reVC/build.sh
- engines/reVC/env.sh
- metadata/packages.json
> Re-add reVC

- engines/opengothic/build.sh
- metadata/packages.json
> opengothic - Update to v1.0.1123

- engines/warzone2100/build.sh
- metadata/packages.json
> warzone2100 - Update to 4.1.0

- engines/openloco/build.sh
- metadata/packages.json
> openloco - Update to 21.07

- engines/warzone2100/build.sh
- metadata/packages.json
> warzone2100 - Update to 4.1.1

- engines/opengothic/build.sh
- metadata/packages.json
> opengothic - Update to v1.0.1177

- engines/warzone2100/build.sh
- metadata/packages.json
> warzone2100 - Update to 4.1.2

- engines/easyrpg-player/assets/run-easyrpg-player.sh
- engines/easyrpg-player/build.sh
- engines/easyrpg-player/env.sh
- metadata/packages.json
> easyrpg-player

- engines/warzone2100/build.sh
- metadata/packages.json
> warzone2100 - Update to 4.1.3

- engines/openloco/build.sh
- metadata/packages.json
> openloco - Update to 21.08

- engines/ftequakeworld/LICENSE
- engines/ftequakeworld/assets/ftequakeworld.sh
- engines/ftequakeworld/build.sh
- engines/ftequakeworld/env.sh
- metadata/packages.json
> ftequakeworld

- engines/rigelengine/build.sh
- metadata/packages.json
> rigelengine - Update to 0.8.0

- engines/vkquake/assets/vkquake.sh
- engines/vkquake/build.sh
- engines/vkquake/env.sh
- metadata/packages.json
> vkquake - Update to latest, adds support for re-release

- engines/vkquake/assets/vkquake.sh
- engines/vkquake/build.sh
- engines/vkquake/env.sh
- metadata/packages.json
> vkquake - Update to 1.11

- engines/rigelengine/build.sh
- metadata/packages.json
Hi, I'm the developer of RigelEngine and recently discovered this project - really cool! And of course I'm happy to see that RigelEngine is bundled as engine.
I saw that you've already updated to the latest 0.8.0 release. Unfortunately, I discovered a bug impacting gameplay shortly after the release, and I had to release a follow-up version 0.8.1. Thought I'd make a PR here so that users of Luxtorpeda will also have the fixed version available.
> rigelengine - Update to 0.8.1

- engines/perimeter/build-ffmpeg.sh
- engines/perimeter/build.sh
- engines/perimeter/env.sh
- metadata/packages.json
> perimeter - Update to 0b355d5

- engines/openloco/build.sh
- metadata/packages.json
> openloco - Update to 21.09

- engines/openloco/assets/run-openloco.sh
- engines/openloco/build.sh
- engines/openloco/env.sh
> openloco - Build for steamrt

- engines/1oom/build.sh
- metadata/packagesruntime.json
> 1oom - Build for steamrt

- engines/augustus/build.sh
- metadata/packagesruntime.json
> augustus - Build for steamrt

- engines/commander-genius/build.sh
- metadata/packagesruntime.json
> commander-genius - Build for steamrt

- engines/ecwolf/build.sh
- metadata/packages.json
- metadata/packagesruntime.json
> ecwolf - Build for steamrt

- common/start_build.sh
- engines/eternaljk/build.sh
- metadata/packagesruntime.json
> eternaljk - Build for steamrt

- engines/jk2mv/build.sh
> jk2mv - Build for steamrt

- engines/ioquake3/build.sh
- metadata/packagesruntime.json
> ioquake3 - Build for steamrt

- engines/quake3e/build.sh
> quake3e - Build for steamrt

- engines/iortcw/build.sh
- metadata/packagesruntime.json
> iortcw - Build for steamrt

- engines/objectn/build.sh
- metadata/packagesruntime.json
> objectn - Build for steamrt

- engines/wrath-darkplaces/build.sh
- metadata/packagesruntime.json
> wrath-darkplaces - Build for steamrt

- engines/yquake2/build.sh
- metadata/packagesruntime.json
> yquake2 - Build for steamrt

- engines/serious-engine/build.sh
- metadata/packagesruntime.json
> serious-engine - Build for steamrt

- engines/chocolate-doom/build.sh
- engines/chocolate-doom/env.sh
- metadata/packagesruntime.json
> chocolate-doom - Build for steamrt

- engines/prboom-plus/build.sh
- engines/prboom-plus/env.sh
- metadata/packagesruntime.json
> prboom - Build for steamrt

- engines/arxlibertatis/build.sh
- engines/arxlibertatis/env.sh
- libraries/boostheaders/build.sh
- libraries/boostheaders/env.sh
- libraries/glm/build.sh
- libraries/glm/env.sh
- metadata/packagesruntime.json
> arxlibertatis - Build for steamrt

- engines/darkplaces-2017/build.sh
- metadata/packagesruntime.json
> darkplaces-2017 - Build for steamrt

- engines/vkquake/build.sh
> vkquake - Build for steamrt

- engines/avp/build.sh
- engines/avp/env.sh
- libraries/libav/build.sh
- libraries/libav/env.sh
- libraries/sdl12compat/build.sh
- libraries/sdl12compat/env.sh
- metadata/packagesruntime.json
> avp - Build for steamrt

- engines/rigelengine/build.sh
- engines/rigelengine/env.sh
- metadata/packagesruntime.json
> rigelengine - Build for steamrt

- engines/realrtcw/build.sh
- metadata/packagesruntime.json
> realrtcw - Build for steamrt

- engines/good-robot/build.sh
- engines/good-robot/env.sh
- libraries/devil/build.sh
- libraries/devil/env.sh
- libraries/freealut/build.sh
- libraries/freealut/env.sh
- metadata/packagesruntime.json
> good-robot - Build for steamrt

- engines/easyrpg-player/build.sh
- engines/easyrpg-player/env.sh
- libraries/libxmp/build.sh
- libraries/libxmp/env.sh
- libraries/wildmidi/build.sh
- libraries/wildmidi/env.sh
- metadata/packagesruntime.json
> easyrpg-player - Build for steamrt

- engines/openxray/build.sh
> openxray - Fix

- engines/openxcom/build.sh
- engines/openxcom/env.sh
- libraries/sdl12gfx/build.sh
- libraries/sdl12gfx/env.sh
- libraries/sdl12image/build.sh
- libraries/sdl12image/env.sh
- libraries/sdl12mixer/build.sh
- libraries/sdl12mixer/env.sh
- libraries/yaml-cpp/build.sh
- libraries/yaml-cpp/env.sh
- metadata/packagesruntime.json
> openxcom - Build for steamrt

- engines/reminiscence/assets/run-flashback.sh
- engines/reminiscence/build.sh
- engines/reminiscence/env.sh
- libraries/libmodplug/build.sh
- libraries/libmodplug/env.sh
- libraries/tremor/build.sh
- libraries/tremor/env.sh
- metadata/packagesruntime.json
> reminiscence - Build for steamrt

- common/lib.sh
- engines/openhexagon/build.sh
> Openhexagon gcc9

- engines/cortex-command/build.sh
> cortex-command - Force re-build

- engines/avp/build.sh
- engines/avp/patches/0001-Remove-RenderSmallFontString_Wrapped-call-in-RenderH.patch
> avp - Fix for other languages

- engines/classic-rbdoom-3-bfg/build.sh
- metadata/packagesruntime.json
> classic-rbdoom-3-bfg - Update to latest commit

- engines/source-sdk-2013/assets/entropy-zero/run-entropy-zero.sh
- engines/source-sdk-2013/assets/metastasis/run-metastasis.sh
- engines/source-sdk-2013/assets/resistance-element/run-resistance-element.sh
- engines/source-sdk-2013/assets/year-long-alarm/run-year-long-alarm.sh
> source-sdk-2013 - Support new errors

- engines/easyrpg-player/build.sh
- engines/easyrpg-player/env.sh
> easyrpg-player - Fix build

- engines/ut2004/assets/run-ut2004.sh
- engines/ut2004/assets/setup-ut2004.sh
- metadata/packagesruntime.json
> ut2004 - Fix missing piece for foxPlayerInput

- engines/runescape/assets/run-runescape.sh
- engines/runescape/build.sh
- engines/runescape/env.sh
- metadata/packagesruntime.json
> runescape - Add back support

- engines/prey2006/assets/autoexec.cfg
- engines/prey2006/assets/run-prey.sh
- metadata/packagesruntime.json
> prey2006 - Fix openal launch error

- metadata/packagesruntime.json
- webui/src/app/app.module.ts
- webui/src/app/packages/packages.component.css
- webui/src/app/packages/packages.component.html
- webui/src/app/packages/packages.component.ts
* Finish cleanup
* Test that client still works with this information
* Ensure that old "information" key is still there for license checks
* Remove processing of information key from angular (but keep limited info in json for legacy)
* add icons/information for manual steps and controller support (the two green/yellow/unknown)
> metadata - Changes to cleanup information

- engines/dosbox-staging/assets/run-dosbox-staging.sh
- engines/dosbox-staging/build.sh
> dosbox-staging - Fix compile

- engines/ut99/assets/run-ut99-469b.sh
- metadata/packagesruntime.json
> ut99 - Use legacy steam runtime

- engines/opengothic/build.sh
- metadata/packagesruntime.json
> opengothic - Update to 1.0.1311

- engines/dosbox-staging/assets/run-dosbox-staging.sh
This new run script enhances out of the box compatibility with most DOS games. Brings my personal number of working DOS games up to 52, from the 4 or so that were working originally.
Most of the remaining broken DOS games are special cases that would be best served by adding the required metadata to packages.json.
Requires: https://github.com/luxtorpeda-dev/luxtorpeda/pull/117
Closes: https://github.com/luxtorpeda-dev/packages/issues/506
> dosbox-staging: Enhance run script

- metadata/packagesruntime.json
Update paths for dosbox-staging
> Metadata: Update dosbox-staging paths

- engines/eduke32/build.sh
- metadata/packagesruntime.json
> eduke32 - Update to 0dff2879

- engines/ruffle/assets/run-ruffle.sh
The swf needs to be launched from Samarost 2 Orginal folder
> ruffle - Improve launch script

- engines/realrtcw/assets/setup-realrtcw.sh
- engines/realrtcw/build.sh
- metadata/packagesruntime.json
> realrtcw - Support steam assets

- engines/openxray/build.sh
- metadata/packagesruntime.json
> openxray - Update to December 2021 RC1

- engines/scummvm/build.sh
- metadata/packagesruntime.json
> scummvm - Update to 2.5.1

- CHANGELOG.md
- metadata/packagesruntime.json
I deleted my fork and started from scratch. Third time's the charm.
> Changed name

- engines/dosbox-staging/build.sh
- engines/dosbox-staging/env.sh
- metadata/packagesruntime.json
https://discordapp.com/channels/514567252864008206/626653390830698516/927735565485498438
> dosbox-staging - Update to 0.78.1

- engines/perimeter/build.sh
- metadata/packagesruntime.json
> perimeter - Update to b7be1c7

- engines/prboom-plus/build.sh
- engines/prboom-plus/env.sh
- libraries/fluidsynth/build.sh
> prboom - Fix fluidsynth

- engines/rbdoom-3-bfg/build.sh
- metadata/packagesruntime.json
> RBDOOM-3-BFG - Update to 1.4.0

- engines/ut2004/build.sh
- engines/ut2004/env.sh
- libraries/sdl12compat/build.sh
> ut2004 - Switch to sdl12compat

- engines/quake4/assets/run-quake4.sh
- engines/quake4/build.sh
- engines/quake4/env.sh
> quake4 - Use sdl12compat

- engines/terminal-recall/assets/maint.config.trcl.xml
- engines/terminal-recall/assets/run-terminal-recall.sh
- engines/terminal-recall/build.sh
- engines/terminal-recall/env.sh
- libraries/openjdk11/build.sh
- libraries/openjdk11/env.sh
> terminal-recall - Update to 14b3d24 and default config

- engines/doom-runner/assets/options-template.json
- engines/doom-runner/assets/run-doom-runner.sh
- engines/doom-runner/assets/run-doomsday.sh
- engines/doom-runner/build.sh
- engines/doom-runner/env.sh
- metadata/packagesruntime.json
> doom-runner

- engines/chocolate-doom/assets/run-chocolate-doom-setup.sh
- engines/chocolate-doom/assets/run-chocolate-heretic-setup.sh
- engines/chocolate-doom/assets/run-chocolate-hexen-setup.sh
- metadata/packagesruntime.json
> chocolate-doom - Add setup

- engines/yquake2/build.sh
- engines/yquake2/env.sh
- metadata/packagesruntime.json
> yquake2 - Update to 4db6534, additional controller support

- engines/opentesarena/assets/run-opentesarena.sh
- engines/opentesarena/build.sh
- engines/opentesarena/env.sh
- metadata/packagesruntime.json
> Added OpenTESArena, in progress engine

- engines/openmw-tes3mp/build.sh
- metadata/packagesruntime.json
> openmw-tes3mp - Update to 0.8.1

- engines/scummvm-latest/assets/run-scummvm.sh
- engines/scummvm-latest/build.sh
- engines/scummvm-latest/env.sh
- metadata/packagesruntime.json
> scummvm-latest

- engines/realrtcw/assets/setup-realrtcw.sh
- engines/realrtcw/build.sh
- engines/realrtcw/patches/0001-Fix-for-compile-error.patch
- metadata/packagesruntime.json
> realrtcw - Update to 4.0 and add defaults for steam deck

- engines/doukutsu-rs/build.sh
- engines/doukutsu-rs/env.sh
- metadata/packagesruntime.json
> doukutsu-rs

- engines/openmw-latest/assets/openmw-launcher.sh
- engines/openmw-latest/assets/openmw.sh
- metadata/packagesruntime.json
* run without launcher and make changes to metadata choice names
* re-test with both original 0.47 mods and completely fresh
> openmw-latest - Fix for missing config line

- engines/gzdoom/env.sh
> gzdoom - Fix compile

- engines/scummvm-latest/build.sh
- metadata/packagesruntime.json
> scummvm-latest - Update to latest RC

- engines/openmw-latest/assets/openmw-launcher.sh
- metadata/packagesruntime.json
> openmw-latest - Add support for launcher

- engines/scummvm-latest/env.sh
- metadata/packagesruntime.json
A small change to support "The 11th Hour" using scummvm-latest.
> Added The 11th Hour to use scummvm-latest

- engines/scummvm-latest/env.sh
- metadata/packagesruntime.json
A small change to support "The 7th Guest" using scummvm-latest.
> Added The 7th Guest to use scummvm-latest

- engines/scummvm-latest/env.sh
- metadata/packagesruntime.json
A small change to support "Sanitarium" using scummvm-latest.
> Added Sanitarium to use scummvm-latest

- engines/opengothic/build.sh
- metadata/packagesruntime.json
> OpenGothic - Update to v1.0.1527

- engines/openloco/build.sh
- metadata/packagesruntime.json
> OpenLoco - Update to 22.06

- engines/openrct2/build.sh
- metadata/packagesruntime.json
> OpenRCT2 - Update to 0.4.1

- engines/classic-rbdoom-3-bfg/build.sh
- engines/classic-rbdoom-3-bfg/patches/e90b31dcc2901f4d8390f8089a8bd43f88c575ea.patch
> classic-rbdoom-3-bfg - Add fix for other languages

- engines/realrtcw/build.sh
- engines/realrtcw/patches/0001-steamshim-fix.patch
- metadata/packagesruntime.json
> realrtcw - Update to 4.0

- engines/dxx-rebirth/build.sh
- metadata/packagesruntime.json
> dxx-rebirth - Update to d1ed53e

- engines/homeworldsdl/assets/run-homeworld.sh
- engines/homeworldsdl/build.sh
- engines/homeworldsdl/env.sh
- metadata/packagesruntime.json
> HomeworldSDL

- engines/doom-retro/build.sh
- metadata/packagesruntime.json
> doom-retro - Update to 4.6.0.1

- engines/ruffle/build.sh
- libraries/openjdk11/build.sh
- libraries/openjdk11/env.sh
- metadata/packagesruntime.json
> ruffle - Update to 576c35a

- engines/cnq3/assets/run-cnq3.sh
- engines/cnq3/build.sh
- engines/cnq3/env.sh
- metadata/packagesruntime.json
> Added cnq3

- engines/crispy-doom/assets/run-crispy-heretic-setup.sh
- engines/crispy-doom/assets/run-crispy-heretic.sh
- engines/crispy-doom/assets/run-crispy-hexen-setup.sh
- engines/crispy-doom/assets/run-crispy-hexen.sh
- engines/crispy-doom/build.sh
- engines/crispy-doom/env.sh
- metadata/packagesruntime.json
> Added Crispy Doom

- engines/inter-doom/assets/run-inter-heretic.sh
- engines/inter-doom/assets/run-inter-hexen.sh
- engines/inter-doom/build.sh
- engines/inter-doom/env.sh
- metadata/packagesruntime.json
> Added International Doom

- engines/crispy-doom/env.sh
> crispy-doom - Add sdl2mixer

- engines/etqw/assets/run-full.sh
- engines/etqw/assets/setup-full.sh
- engines/etqw/assets/uninstall-full.sh
- metadata/packagesruntime.json
This has been tested to successfully install and launch the full version of ETQW as an expansion to issue #353. This can likely be backported to the demo as well assuming a good download location exists for that linux installer and unzips the same way.
* [ X ] Have you verified that the changes are isolated to the features or fixes you are wanting to do?
* [ X ] Have you tested at least one of the engines to ensure that your changes do not break existing workflow?
* [ X ] Have you described what your changes are accomplishing?
> etqw - Add auto download/install support for full game

- engines/inter-doom/assets/run-inter-doom.sh
- engines/inter-doom/assets/run-inter-hexen.sh
- engines/inter-doom/build.sh
- engines/inter-doom/env.sh
- metadata/packagesruntime.json
> inter-doom - Add support for doom

- engines/inter-doom/build.sh
- metadata/packagesruntime.json
> inter-doom - Update to 6.0

- engines/dosbox-staging/build.sh
- engines/dosbox-staging/env.sh
- metadata/packagesruntime.json
> dosbox-staging - Update to 0.79.0

- engines/gzdoom/env.sh
> gzdoom - Fluidsynth 2 fix

- engines/iortcw/build.sh
- engines/iortcw/patches/0001-Load-crashing-fixes.patch
- metadata/packagesruntime.json
> iortcw - Update to 6cbc480

- engines/dosbox-staging/build.sh
- metadata/packagesruntime.json
> dosbox-staging - Update to 0.79.1

- engines/unreal-gold/assets/README.txt
am i missing something? is the .7z supposed to be extracted automatically by some step? i had to do it manually.
> unreal-gold - Update README

- engines/openrct2/build.sh
- metadata/packagesruntime.json
> openrct2 - Update to 0.4.2

- engines/openxcom-oxce/build.sh
- metadata/packagesruntime.json
> openxcom-oxce - Update to 7.7.6

- engines/doom-runner/build.sh
- libraries/qt5/build.sh
> doom-runner - Fix compile issues

- engines/vkquake/assets/vkquake.sh
- engines/vkquake/build.sh
- metadata/packagesruntime.json
> vkquake - Update to 1.22

- engines/doom-retro/build.sh
- metadata/packagesruntime.json
> doom-retro - Update to 4.7

- engines/serious-engine/build.sh
- metadata/packagesruntime.json
> SeriousSamClassic-VK - Update to 1.10.3

- engines/doom-retro/build.sh
- libraries/sdl2/build.sh
- metadata/packagesruntime.json
> doom-retro - Update to 4.7.1

- engines/unreal-gold/assets/README.txt
- engines/unreal-gold/assets/run-unreal.sh
- engines/unreal-gold/build.sh
- engines/unreal-gold/env.sh
- metadata/packagesruntime.json
> unreal-gold - Update to 227j

- engines/openrct2/build.sh
- metadata/packagesruntime.json
> OpenRCT2 - Update to 0.4.3

- engines/unreal-gold/assets/run-unreal.sh
- engines/unreal-gold/env.sh
- libraries/libxmp32/build.sh
- libraries/libxmp32/env.sh
- metadata/packagesruntime.json
Having issues finding openal:
```
Failed to load ALAudio: Can't find file for package ALAudio..
Failed to load "Class ALAudio.ALAudioSubsystem": Can't find file for package ALAudio..
Can't find file for package ALAudio.
appError called:
Can't find file for package ALAudio.
Executing UObject::StaticShutdownAfterError
SDL2: Executing USDL2Client::ShutdownAfterError
UOpenGLRenderDevice::ShutdownAfterError
```
That should be included with the steam runtime, so check if 32-bit exists, and maybe soft-link in like other engines.
> unreal-gold - Switch to 32-bit

- engines/doom-retro/build.sh
- metadata/packagesruntime.json
> doom-retro - Update to 4.7.2

- engines/raze/build.sh
- metadata/packagesruntime.json
> raze - Update to 1.6.1

- engines/dosbox-staging/build.sh
- engines/dosbox-staging/env.sh
- metadata/packagesruntime.json
> dosbox-staging - Update to 0.80.0

- engines/openmw-latest/build.sh
Hi!
I've noticed that the openmw-shaders commit used in the build script https://github.com/luxtorpeda-dev/packages/blob/master/engines/openmw-latest/build.sh#L17 is more than 6 months old. Since then there was a lot of fixes and improvements. I've updated the commit hash to the most recent one.
> Checkout the most recent commit in openmw-shaders repo

- engines/inter-doom/build.sh
- metadata/packagesruntime.json
> inter-doom - Update to 6.1

- engines/warzone2100/build.sh
- metadata/packagesruntime.json
> warzone2100 - Update to 4.3.3

- engines/dosbox-staging/build.sh
- metadata/packagesruntime.json
> dosbox-staging - Update to 0.80.1

- engines/raze/build.sh
- metadata/packagesruntime.json
> raze - Update to 1.6.2

- engines/openloco/build.sh
- engines/openloco/env.sh
- metadata/packagesruntime.json
> OpenLoco - Update to v22.12

- engines/ecwolf/build.sh
- metadata/packagesruntime.json
> ecwolf - Update to 1.4.0

- engines/openra/assets/run-openra-tiberian.sh
- engines/openra/build.sh
- engines/openra/env.sh
- metadata/packagesruntime.json
> Add openra-tiberiandawnhd

- engines/doukutsu-rs/build.sh
- metadata/packagesruntime.json
> doukutsu-rs - Update to 0.100.0-beta5

- engines/vanilla-conquer/assets/run-vanilla-conquer-ra.sh
- engines/vanilla-conquer/assets/run-vanilla-conquer-td.sh
- engines/vanilla-conquer/build.sh
- engines/vanilla-conquer/env.sh
- metadata/packagesruntime.json
Follow instructions here to create RA folder (create a linuxdata-ra folder with everything symlinked) - https://github.com/TheAssemblyArmada/Vanilla-Conquer/wiki/Installing-VanillaRA#remastered-collection
Make note about RA soviet limitations.
Add launch options so that there is remastered openra, vanilla conquer ra, vanilla conquer td
> Vanilla Conquer

- engines/ozymandias/build.sh
- engines/ozymandias/env.sh
- metadata/packagesruntime.json
> Added Ozymandias

- engines/opengothic/build.sh
- engines/opengothic/env.sh
- metadata/packagesruntime.json
> OpenGothic - Update to v1.0.1891

- engines/openmw/build.sh
- libraries/boost/build.sh
- libraries/bullet3/build.sh
- libraries/mygui/build.sh
- libraries/openmwosg/build.sh
- libraries/unshield/build.sh
> openmw - Performance investigation

- engines/openxcom-oxce/build.sh
- metadata/packagesruntime.json
> openxcom-oxce - Update to 7.8

- engines/ironwail/env.sh
- libraries/curl/build.sh
- libraries/curl/env.sh
> ironwail - Fix

- engines/odamex/build.sh
- metadata/packagesruntime.json
Just updating the Odamex build script to use the most recent release.
> Odamex - Update to 10.3.0

- engines/doom64ex-plus/LICENSE
- engines/doom64ex-plus/assets/run-doom64ex-plus.sh
- engines/doom64ex-plus/build.sh
- engines/doom64ex-plus/env.sh
- metadata/packagesruntime.json
> doom64ex-plus

- engines/avp/build.sh
- engines/avp/patches/0001-allow-unlimited-saves.patch
> avp - Allow for unlimited saves

- engines/crispy-doom/build.sh
- metadata/packagessniper.json
> crispy-doom - Update to 6.0

- engines/exhumed/build.sh
- metadata/packagessniper.json
> exhumed - Update to 09143c3

- engines/hammerofthyrion/build.sh
- metadata/packagessniper.json
> Hammer of Thyrion - Update to f22de3d

- engines/notblood/build.sh
- metadata/packagessniper.json
> notblood - Upgrade to 7813e43

- engines/openjk/build.sh
- metadata/packagessniper.json
> openjk - Update to d3e8c8d

- engines/openloco/build.sh
- engines/openloco/env.sh
- metadata/packagessniper.json
> OpenLoco - Update to v23.03

- engines/doomseeker/build.sh
- libraries/qt5tools/build.sh
- metadata/packagessniper.json
> doomseeker - Update to 9fab457

- engines/ctp2/assets/run-ctp2.sh
- engines/ctp2/build.sh
- engines/ctp2/env.sh
> ctp2 - Fix for sniper

- engines/cortex-command/assets/run-cortex-command.sh
- engines/cortex-command/build.sh
- engines/cortex-command/env.sh
- libraries/lua/build.sh
- libraries/lua/env.sh
- libraries/lua/lua.pc
- libraries/lua/patches/liblua.so.patch
- metadata/packagessniper.json
> cortex-command - Fix for sniper

- common/lib.sh
- common/start_build.sh
- common/vcpkg_support/custom-triplets/x64-linux-dynamic.cmake
- engines/fs2open/build.sh
- engines/fs2open/env.sh
- engines/fs2open/vcpkg.json
> Use vcpkg for libraries

- common/lib.sh
- engines/chocolate-doom/build.sh
- engines/chocolate-doom/env.sh
- engines/chocolate-doom/vcpkg.json
> chocolate-doom - Switch to vcpkg

- engines/crispy-doom/env.sh
- engines/crispy-doom/vcpkg.json
> crispy-doom - Use vcpkg

- engines/doom-retro/env.sh
- engines/doom-retro/vcpkg.json
> doom-retro - Use vcpkg

- engines/crispy-doom/vcpkg.json
> crispy-doom - Fix

- common/lib.sh
- engines/dsda-doom/build.sh
- engines/dsda-doom/env.sh
- engines/dsda-doom/vcpkg.json
vcpkg libs are not being found by cmake
> dsda-doom - Use vcpkg

- metadata/packagessniper.json
Adds support for AnodyneFNA, using the repository's release binaries.
Closes #917
> Add support for AnodyneFNA

- engines/openmw/build.sh
- engines/openmw/env.sh
- libraries/bullet3/build.sh
- libraries/openmwosg/build.sh
- libraries/qt5/build.sh
> openmw - Updates

- engines/runescape/assets/run-runescape.sh
- engines/runescape/build.sh
- engines/runescape/env.sh
- libraries/ar/build.sh
- libraries/ar/env.sh
> runescape - Switch to ar

- engines/scummvm/build.sh
- metadata/packagessniper_v2.json
This small changes updates the scummvm version from 2.7.0 to 2.7.1, which [was recently tagged](https://github.com/scummvm/scummvm/releases/tag/v2.7.1).
> Update scummvm to 2.7.1

- common/lib.sh
- engines/crispy-doom/vcpkg.json
> crispy-doom - Fix for vcpkg & sdl2-mixer

- engines/eduke32/env.sh
> eduke32 - Switch to vcpkg

- engines/dxx-rebirth/env.sh
- engines/dxx-rebirth/vcpkg.json
> dxx-rebirth - Switch to vcpkg

- engines/openmw/build.sh
- engines/openmw/env.sh
- libraries/xcb/build.sh
- libraries/xcb/env.sh
> openmw - xcb cleanup

- engines/prboom-plus/env.sh
- engines/prboom-plus/vcpkg.json
> prboom-plus - Switch to vcpkg

- engines/gzdoom/env.sh
- engines/gzdoom/vcpkg.json
> gzdoom - Switch to vcpkg

- engines/hammerofthyrion/build.sh
- engines/hammerofthyrion/env.sh
- engines/hammerofthyrion/vcpkg.json
> hammerofthyrion - Switch to vcpkg

- engines/reminiscence/build.sh
- engines/reminiscence/env.sh
- engines/reminiscence/vcpkg.json
> reminiscene - Switch to vcpkg

- engines/scummvm/env.sh
- engines/scummvm/vcpkg.json
> scummvm - Switch to vcpkg

- common/lib.sh
- engines/perimeter/build.sh
- engines/perimeter/env.sh
- engines/perimeter/vcpkg.json
- metadata/packagessniper_v2.json
> perimeter - Switch to vcpkg

- engines/chocolate-doom/build.sh
- metadata/packagessniper_v2.json
> chocolate-doom - Update to 20abc8b

- engines/openapoc/build.sh
- engines/openapoc/env.sh
- engines/openapoc/vcpkg.json
> openapoc - Switch to vcpkg

- metadata/packagessniper_v2.json
> Afterlife Missing appid

- metadata/packagessniper_v2.json
run-dream-one-up.sh was missing. I'm guessing this is the problem?
> New dreamm package

- metadata/packagessniper_v2.json
> wrong file name

- engines/hiigara/assets/run-homeworld.sh
- engines/hiigara/build.sh
- engines/hiigara/env.sh
- metadata/packagessniper_v2.json
> Add support for Hiigara engine

- engines/doom-retro/build.sh
- metadata/packagessniper_v2.json
> DOOM Retro - Update to 5.0

- metadata/packagessniper_v2.json
> Fix for 6030 and 299030

- engines/inter-doom/build.sh
- engines/inter-doom/env.sh
- metadata/packagessniper_v2.json
> International Doom - Update to 7.2.1

- engines/eternity/LICENSE
- engines/eternity/assets/master.csc
- engines/eternity/assets/run-eternity.sh
- engines/eternity/build.sh
- engines/eternity/env.sh
- engines/eternity/vcpkg.json
- metadata/packagessniper_v2.json
> Add Eternity Engine

- .github/workflows/check_download_status.yml
- metadata/packagessniper_v2.json
> Scheduled download check

- .github/workflows/check_download_status.yml
- metadata/packagessniper_v2.json
> Scheduled workflow working

- metadata/packagessniper_v2.json
> Daggerfall Unity - Update to 0.16.3 RC

- engines/scummvm/build.sh
- metadata/packagessniper_v2.json
A small PR to update scummvm to the 2.8.0 release
> Update scummvm to 2.8.0

- engines/odamex/build.sh
- metadata/packagessniper_v2.json
> odamex - Update to 0880dd0

- engines/crispy-doom/vcpkg.json
> crispy-doom - add libflac

- engines/dosbox-staging/build.sh
- engines/dosbox-staging/env.sh
- metadata/packagessniper_v2.json
> DOSBox Staging - Update to 0.81.0

- .github/workflows/build_engine.yml
- .github/workflows/test_engine.yml
- engines/dhewm3/build.sh
- engines/doom-runner/build.sh
2024-02-08T16:09:12.0505544Z Error copying ../../lib/libQt5Core.so.5.15.7 to /__w/packages/packages/libraries/local/qt5/lib/libQt5Core.so.5.15.7: Failure to write block
2024-02-08T16:09:12.0507677Z make[3]: *** [Makefile:55539: install_target] Error 3
> workflows - remove tools to save space on gh actions

- engines/dosbox-staging/build.sh
> dosbox-staging - Update to new 0.81.0 tag

- .github/workflows/check_engine_releases.yml
> Check for new engine releases

- engines/vanilla-conquer/build.sh
- engines/vanilla-conquer/env.json
- metadata/packagessniper_v2.json
> vanilla-conquer - Add support for new releases

- engines/gzdoom/assets/run-cleandoom.sh
- metadata/packagessniper_v2.json
Waiting on https://github.com/popcar2/CleanDoom/issues/3
> Add cleandoom

- engines/nugget-doom/assets/run-nugget-doom.sh
- engines/nugget-doom/build.sh
- engines/nugget-doom/env.json
- engines/nugget-doom/vcpkg.json
- metadata/packagessniper_v2.json
> Add Nugget Doom

- engines/descent3/assets/run-descent3.sh
- engines/descent3/build.sh
- engines/descent3/env.json
- engines/descent3/vcpkg.json
- metadata/packagessniper_v2.json
> Add Descent3

- engines/surreal_engine/build.sh
- engines/surreal_engine/env.json
- metadata/packagessniper_v2.json
> Add SurrealEngine

- engines/classic-rbdoom-3-bfg/build.sh
- engines/classic-rbdoom-3-bfg/env.json
- metadata/packagessniper_v2.json
> classic-rbdoom-3-bfg - Update to fd2d166

- engines/relentless-frontier/LICENSE
- engines/relentless-frontier/assets/run-gzdoom.sh
- engines/relentless-frontier/build.sh
- engines/relentless-frontier/env.json
- engines/relentless-frontier/vcpkg.json
- metadata/packagessniper_v2.json
> Add RFGZDoom

- engines/ut2004/assets/run-ut2004-standard-no-sdlcompat.sh
- engines/ut2004/assets/run-ut2004-standard.sh
- engines/ut2004/assets/run-ut2004.sh
Modified to take arguments, mostly to aid my user-packages.json to download & launch Killing Floor Mod 2.52 and Alien Swarm v1.34 but let me know if you'd rather have those mods in the package, I don't think the Luxtorpeda project is for that
> UT2004 run scripts fix

- engines/chocolate-doom/build.sh
- engines/chocolate-doom/env.json
- metadata/packagessniper_v2.json
> chocolate-doom - Update to 3.1.0

- engines/gzdoom/assets/run-gzdoom-2-master-levels-combo.sh
- engines/gzdoom/assets/run-gzdoom-2-master-levels-old.sh
- engines/gzdoom/assets/run-gzdoom-2-master-levels.sh
- engines/gzdoom/assets/run-gzdoom-hedon.sh
- engines/gzdoom/assets/run-gzdoom-local.sh
- engines/gzdoom/assets/run-gzdoom.sh
- engines/gzdoom/build.sh
- engines/gzdoom/env.json
- libraries/zmusic/build.sh
- metadata/packagessniper_v2.json
Still need to bump version on json file and force gzdoom to use the correct non broken renderer 
Then look at https://github.com/luxtorpeda-dev/packages/issues/1360
```
gzdoom +vid_backend 1
```
> Update gzdoom 

- engines/dosbox-staging/build.sh
- engines/dosbox-staging/env.json
- metadata/packagessniper_v2.json
> Ds staging fixes

- engines/dii4a/env.json
- metadata/packagessniper_v2.json
> dii4a - Update to 54bcfd3

- engines/openxcom-oxce/env.json
- metadata/packagessniper_v2.json
> openxcom-oxce - Update to 7.15

- engines/commander-genius/env.json
- metadata/packagessniper_v2.json
> commander-genius - Update to 3.5.2

- engines/eternity/build.sh
- engines/eternity/env.json
- metadata/packagessniper_v2.json
> eternity engine - Update to 4.04.02

- engines/1oom/build.sh
- engines/1oom/env.json
- metadata/packagessniper_v2.json
> 1oom - Update to new fork

- engines/doom64ex-plus/build.sh
- engines/doom64ex-plus/env.json
- metadata/packagessniper_v2.json
> doom64 - Update to 4.0.0.3.SDL.3.1.3

- engines/doukutsu-rs/build.sh
- engines/doukutsu-rs/env.json
- metadata/packagessniper_v2.json
> doukutsu-rs - Update to 0.102.0-beta7

- engines/nblood/build.sh
- engines/nblood/env.json
- metadata/packagessniper_v2.json
> nblood - Update to r14204

- engines/odamex/build.sh
- engines/odamex/env.json
- metadata/packagessniper_v2.json
> Odamex - update to 11

- engines/cnq3/build.sh
- engines/cnq3/env.json
- metadata/packagessniper_v2.json
> cnq3 - Update to 1.53

- engines/solarus/build.sh
- engines/solarus/env.json
- metadata/packagessniper_v2.json
> solarus - Update to v1.6.5+cicd1

- engines/fs2open/build.sh
- engines/fs2open/env.json
- metadata/packagessniper_v2.json
> fs2open - Update to release_24_2_0

- engines/doomseeker/build.sh
- engines/doomseeker/env.json
- metadata/packagessniper_v2.json
> doomseeker - Update to 1.5.3

- engines/q2pro/build.sh
- engines/q2pro/env.json
- metadata/packagessniper_v2.json
> q2pro -  update to r3510

- engines/gardensofkadesh/build.sh
- engines/gardensofkadesh/env.json
- engines/gardensofkadesh/vcpkg.json
- metadata/packagessniper_v2.json
> Gardens of Kadesh - Update to 1.2.0

- engines/quake3e/build.sh
- engines/quake3e/env.json
- metadata/packagessniper_v2.json
> quake3e - Update to 2024-10-14

- engines/reminiscence/build.sh
- engines/reminiscence/env.json
- metadata/packagessniper_v2.json
> reminisncene - Update to 0.5.3

- metadata/packagessniper_v2.json
> daikatana - Move to github

- engines/7kaa/build.sh
- engines/7kaa/env.json
- metadata/packagessniper_v2.json
> 7kaa - Update to use new sourceforge repo

- engines/cnc-red-alert/assets/run-cnc-and-ra-ra.sh
- engines/cnc-red-alert/assets/run-cnc-and-ra-td.sh
- engines/cnc-red-alert/build.sh
- engines/cnc-red-alert/env.json
- metadata/packagessniper_v2.json
> Add cnc-and-red-alert

- .github/workflows/build_engine.yml
- .github/workflows/test_engine.yml
- CHANGELOG.md
- engines/1oom/build.sh
- engines/ioquake3/build.sh
> Matrix switch

- engines/doomseeker/assets/run-doomseeker.sh
- engines/doomseeker/build.sh
> fix doomseeker

- engines/easyrpg-player/build.sh
- engines/easyrpg-player/env.json
- engines/easyrpg-player/vcpkg.json
- metadata/packagessniper_v2.json
> easyrpg-player - Update to 0.8.1

- common/lib.sh
- common/start_build.sh
- engines/helion/assets/run-helion.sh
- engines/helion/build.sh
- engines/helion/env.json
- engines/open-ig/build.sh
- engines/open-ig/env.json
- engines/quake-injector/build.sh
- engines/quake-injector/env.json
- engines/ruffle/env.json
- engines/terminal-recall/env.json
- libraries/openjdk11/build.sh
- libraries/openjdk11/env.sh
- metadata/packagessniper_v2.json
> Move to apt openjdk & dotnet

- engines/yquake2/build.sh
- engines/yquake2/env.json
- metadata/packagessniper_v2.json
> yquake2 - Update to QUAKE2_8_50

- engines/skin-deep/assets/run-dhewm3.sh
- engines/skin-deep/build.sh
- engines/skin-deep/env.json
- metadata/packagessniper_v2.json
> Add skin deep

- engines/skin-deep/env.json
- metadata/packagessniper_v2.json
> skin-deep - switch to main branch

- engines/doom-runner/build.sh
- engines/doom-runner/env.json
- metadata/packagessniper_v2.json
> doom-runner - Update to 9a7cce2

- engines/chocolate-quake/LICENSE
- engines/chocolate-quake/assets/chocolate-quake.sh
- engines/chocolate-quake/build.sh
- engines/chocolate-quake/env.json
- metadata/packagessniper_v2.json
> chocolate-quake

- engines/raze/build.sh
- engines/raze/env.json
- metadata/packagessniper_v2.json
> raze - Update to 1.11.0

- engines/doom64ex-plus/assets/run-doom64ex-plus.sh
- engines/doom64ex-plus/build.sh
- engines/doom64ex-plus/env.json
- metadata/packagessniper_v2.json
> Switch to doom64ex-minus

- engines/classic-rbdoom-3-bfg/build.sh
- engines/classic-rbdoom-3-bfg/env.json
- metadata/packagessniper_v2.json
> classic-rbdoom-3-bfg - Update to c3cd7f9

- engines/openxray/build.sh
- engines/openxray/env.json
- engines/openxray/vcpkg.json
- metadata/packagessniper_v2.json
> openxray - Update to latest

- engines/gzdoom/assets/run-gzdoom-local.sh
- engines/gzdoom/build.sh
- libraries/zmusic/build.sh
> gzdoom - Update zmusic to latest
